name: Make Release

on:
  workflow_call:
    inputs:
      pre-release-mode:
        description: "Whether or not to tag versions as pre-release versions"
        required: false
        type: boolean
      
      custom-pre-release-script:
        description: "Path to a custom pre-release script in the repository"
        required: false
        type: string

jobs:
  changelog-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ github.token }}
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: ShapeGames/conventional-changelog-action@releases/v3
        with:
          github-token: ${{ github.token }}
          skip-version-file: 'true'
          fallback-version: '1.0.0'
          skip-commit: 'true'
          tag-prefix: ''
          pre-release: "${{ inputs.pre-release-mode }}"
          pre-release-bumps-minor: 'true'

      - name: Stop if needed
        if: ${{ steps.changelog.outputs.changelog == null }}
        run: exit 1

      - name: Run Custom Pre-Release Script
        if: inputs.custom-pre-release-script != ''
        env:
          NEW_TAG: ${{ steps.changelog.outputs.tag }}
        run: |
          if [ -f "${{ inputs.custom-pre-release-script }}" ]; then
            chmod +x "${{ inputs.custom-pre-release-script }}"
            "${{ inputs.custom-pre-release-script }}"
          else
            echo "Custom pre-release script not found"
            exit 1
          fi

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: ${{ inputs.pre-release-mode }}

      - name: Post to Slack
        run: |
          curl -X POST ${{ secrets.CHANGELOG_SLACK_WEBHOOK_URL }} \
          --data-binary @- << EOF
          {
              "text": "*${{ github.event.repository.name }}*\n_Author: ${GITHUB_ACTOR}_\n\n${{ steps.changelog.outputs.changelog }}",
              "username": "Changelog",
              "icon_emoji": ":unicorn_face:",
              "channel": "#changelog-ios"
          }
          EOF
