name: Commons

on:
  push:
    branches: [ main, master ]

jobs:
  make-release:
    uses: n3d1117/test_commons/.github/workflows/make-release.yml@main
    secrets: inherit
    with:
      before-release-script: 'scripts/update-sdk-version.sh'
