name: Commons

on:
  push:
    branches: [ main, master ]

jobs:
  pr-workflow:
    name: Release Workflow
    uses: n3d1117/test_action/.github/workflows/make-release.yml@main
    secrets: inherit
    with:
      before-release: |
        echo "Running a custom task before creating the release."
        echo "The release tag is: ${{ steps.changelog.outputs.tag }}"
