name: Commons

on:
  push:
    branches: [ main, master ]

jobs:
  make-release:
    uses: ./.github/workflows/make-release.yml
    secrets: inherit
    # with:
    #   custom-pre-release-script: './scripts/pre-release.sh'
