name: Commons

on:
  push:
    branches: [ main, master ]

jobs:
  pr-workflow:
    name: Release Workflow
    uses: ShapeGames/commons-ios/.github/workflows/common-release-workflow.yml@main
    secrets: inherit
    with:
      custom-pre-release-script: './scripts/pre-release.sh'
